spring.application.name=Contest

spring.datasource.url=jdbc:postgresql://localhost:5432/contest
spring.datasource.username=contest
spring.datasource.password=contest

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
